### ISSUE TITLE
Accordion is not being closing

### ISSUE THREAD

**Issue by MahmudX** [Pienteger/Pienteger.github.io#13]
The accordion inside the FAQ section is not closing.

[openai_pricing](https://pienteger.com/marketplace/openai_pricing)

**Comment by Hasibul-Hasan-ofcs** [comment]
Okay vi I'll take a look at it... One thing ... what about the footer UI? If it needs to be updated also..then let me know about the categories I should split them into... It looks kinda terrible haha

**Comment by MahmudX** [comment]
- Go ahead. 🏃🏻‍♂️
- Do what's necessary. 🫡 
- Unleash your creativity. 👍🏼
