### ISSUE TITLE
Link blog to the original site

### ISSUE THREAD

**Issue by MahmudX** [Pienteger/Pienteger.github.io#6]
Please link the following url to the suitable place - [http://blog.pienteger.com/](http://blog.pienteger.com/)

**Comment by Hasibul-Hasan-ofcs** [comment]
@MahmudX vi eta headerComponent e add kore dilam

**Comment by MahmudX** [comment]
@Hasibul-Hasan-ofcs Please create a pull request and link with the issue.

**Comment by MahmudX** [comment]
Good work btw.
