### ISSUE TITLE
Create OpenAi Overview page

### ISSUE THREAD

**Issue by MahmudX** [Pienteger/Pienteger.github.io#7]

**Comment by Hasibul-Hasan-ofcs** [comment]
https://openai.com/research/overview - @MahmudX  vi this one?

**Comment by MahmudX** [comment]
Main website er sathe link kore dao. Jeita replicate korte cheyecjilam oi page ar nai dekhchi.

**Comment by Hasibul-Hasan-ofcs** [comment]
eta kon jaigai linked hobe?

**Comment by MahmudX** [comment]
![image](https://user-images.githubusercontent.com/16564582/223181123-b85e4816-2f40-4cdd-9807-7259f4effca6.png)
